exchange:
  currency:
    api:
      uri: https://api.apilayer.com/currency_data/live
      key: eipMczgiQB0BDmiHx2dX2dv9pPjGxXnh

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
#    com.mangkyu.openfeign.app.openfeign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
